feat(markdown): allow overwriting plugins
nuxt/content pull request #1226
Opened 2022-06-07 12:40 UTC by farnabaz

### 🔗 Linked issue
resolves #1212

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-06-08 11:31 UTC, Tahul requested changes
Hey :), this is excellent work!

Could you tell if it is possible to test this case?

Like testing each possible way to import/update/overwrite plugins configurations?

That would also be really helpful for me to update the documentation.

2022-06-09 11:50 UTC, Tahul approved these changes

2022-06-09 11:51 UTC, Tahul commented
Great job @farnabaz, LGTM now :)

We'll just need to open an issue to track support for local remark/rehype plugins.

2022-06-09 11:58 UTC, farnabaz reviewed
chore: remove unused links

2022-06-09 12:04 UTC, merged