Docs/fix typo
nuxt/content pull request #1634
Opened 2022-10-23 11:03 UTC by selemondev

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2022-10-23 11:52 UTC, nobkd commented on docs/content/3.guide/3.recipes/1.sitemap.md
> +We will be utilising the [server routes](https://v3.nuxtjs.org/guide/features/server-routes) available within Nuxt, and to do so you'll need to create the `server/` directory within your website`s ro
```suggestion
We will be utilising the [server routes](https://v3.nuxtjs.org/guide/features/server-routes) available within Nuxt, and to do so you'll need to create the `server/` directory within your website's root directly.
```

2022-10-23 11:52 UTC, nobkd commented on docs/content/3.guide/1.writing/7.document-driven.md
> +
```suggestion
It comes with a direct binding between your page's meta data to the OpenGraph tags using the [useContentHead() composable](/api/composables/use-content-head), providing effective SEO with no configuration.
```

2022-10-23 11:53 UTC, nobkd requested changes

2022-10-23 11:53 UTC, nobkd commented on docs/content/3.guide/1.writing/7.document-driven.md
> +
```suggestion
It comes with a direct binding between your page's meta data to the OpenGraph tags using the [useContentHead() composable](/api/composables/use-content-head), providing effective SEO with no configuration.
```

2022-10-23 11:53 UTC, nobkd commented on docs/content/3.guide/3.recipes/1.sitemap.md
> +We will be utilising the [server routes](https://v3.nuxtjs.org/guide/features/server-routes) available within Nuxt, and to do so you'll need to create the `server/` directory within your website`s ro
```suggestion
We will be utilising the [server routes](https://v3.nuxtjs.org/guide/features/server-routes) available within Nuxt, and to do so you'll need to create the `server/` directory within your website's root directly.
```

2022-10-24 13:15 UTC, Atinux approved these changes

2022-10-24 13:15 UTC, merged