feat(markdown): keep meta from fenced code block
nuxt/content pull request #1800
Opened 2023-01-06 14:52 UTC by Qwertovsky

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Don't drop a info from fenced code
````markdown
```javascript[file.js]{4-6,7} meta-info=val
export default () => {
  console.log('Code block')
}
```
````
So `meta-info=val` will be accessible from the document tree after parsing. Property `meta` will be next to `language`, `filename`, `highlights`.
It can help to do other modifications with remark plugins, transformers, or ProseCode component.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2023-01-11 17:11 UTC, farnabaz approved these changes
LGTM 👍

2023-01-11 17:14 UTC, farnabaz commented
@Qwertovsky do you mind fixing linter issues?

2023-01-11 17:32 UTC, nobkd requested changes

2023-01-11 17:32 UTC, nobkd commented on test/features/parser-markdown.ts
> +          '```'
```suggestion
            '```ts [file.ts]{4-6,7} other code block info',
            'let code = undefined;',
            'return code;',
            '```'
```

2023-01-12 11:43 UTC, merged

2023-09-25 23:28 UTC, SimonScholz commented
The sample mentioned above using `{4-6,7}` is not targeting the sample code since it has only 3 lines.

![image](https://github.com/nuxt/content/assets/7559962/584096c3-466d-414d-9d2d-a5c5f27af2a1)

This is really unfortunate because I am currently facing the issue that no different highlighting is applied to the lines in brackets, e.g., `{4-6,7}` 
Shall I open a bug for this or is the `{4-6,7}` somehow not supported?

2023-09-26 05:46 UTC, nobkd commented
@SimonScholz
Thos should be fixed with nuxt-modules/mdc#21 and will be fixed when the package is updated in Content. If that's the case, then the edge channel should already have the fix. Otherwise it should be fixed when a new version of Content gets released