feat(markdown): flag that the excerpt is a copy of the body
nuxt/content pull request #1801
Opened 2023-01-06 15:06 UTC by Qwertovsky

### 🔗 Linked issue

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
If there is no `` divider in the text then the excerpt is a copy of full content.

This change adds new boolean variable `excerptIsBody` into the document next to `excerpt`.

- It can help to improve performance and don't process the excerpt (just make a copy of body).
- It can help to don't show link to full text if there is nothing to read more. 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2023-01-06 16:16 UTC, Atinux commented
What about making the excerpt empty instead to avoid double payload?

2023-01-09 10:03 UTC, farnabaz requested changes
Instead of having an extra field in the document, we should clear the `excerpt` value.

It also reduces the document sizes and smaller chunks.

2023-01-10 00:18 UTC, Qwertovsky commented
I made changes. Now the excerpt is undefined.

By default, `<ContentRenderer>`  still shows body.
```ts
    // Get body from value
    let body = (value.body || value) as MarkdownNode
    if (ctx.excerpt && value.excerpt) {
      body = value.excerpt
    }
```
But this PR could be breaking change for some cases. If the excerpt is used as content property in code.

2023-01-13 13:12 UTC, farnabaz approved these changes

2023-01-13 13:13 UTC, merged