docs: update content list query example
nuxt/content pull request #1901
Opened 2023-02-11 03:35 UTC by PatrikBird

### 🔗 Linked issue
No issue found, do I need to create one for this little change?

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR simply updates/fixes the query example: The `sort` parameter must be an array hence the type: `SortOptions[]`

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2023-02-11 16:50 UTC, nobkd requested changes

2023-02-11 16:50 UTC, nobkd commented on docs/content/4.api/1.components/2.content-list.md
> +const query: QueryBuilderParams = { path: '/articles', where: { layout: 'article' }, limit: 5, sort: [{ date: -1 }] }
```suggestion
const query: QueryBuilderParams = { path: '/articles', where: [{ layout: 'article' }], limit: 5, sort: [{ date: -1 }] }
```

2023-02-11 16:51 UTC, nobkd commented
> No issue found, do I need to create one for this little change?

No. You only add issues to that section, if you know of any issue. That's, to allow the maintainers to close those when the PR was merged.

2023-02-17 16:48 UTC, farnabaz approved these changes
Thanks 👍

2023-02-17 16:48 UTC, merged