perf(dev-cache): improve localhost markdown page navigation performance (when having 2,000+ pages)
nuxt/content pull request #2675
Opened 2024-06-21 09:55 UTC by coffeephile

### 🔗 Linked issue

https://github.com/nuxt/content/issues/2674

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #2674 

Navigating between markdown pages on localhost (dev server) is very slow when dealing with 2,000+ markdown pages.
(Please refer to linked issue for demo and reproduction)

By using `cachedContents` on localhost as well (not only during build time) this issue can be resolved.
In order to keep hot reload working, the cache gets flushed when a file change is detected.

I confirmed my fix to be working for my use case, however I'm not sure if I am breaking anything else in the process, so any advice or help is welcome.
This PR should be considered a first draft, rather than a perfect solution. 🙇‍♂️ 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2024-06-21 11:43 UTC, farnabaz requested changes
By removing the prerendering check, we are changing the behavior of the production environment too.
We should add back prerendering check and add logic to handle dev mode

2024-06-21 11:43 UTC, farnabaz commented on src/module.ts
> +      addServerPlugin(resolveRuntimeModule("./server/plugins/refresh-cache"));
We should add this plugin only in development mode

2024-06-21 11:43 UTC, farnabaz commented on src/runtime/server/storage.ts
> +    if (cachedContents.length) {
Shall we keep `isPrerendering` and add a condition for dev?

```suggestion
    if ((isPrerendering || !isProduction) && cachedContents.length) {
```

2024-06-21 11:43 UTC, farnabaz commented on src/runtime/server/storage.ts
> +        cachedContents = result as ParsedContent[]
Here we can add back prerendering and check for dev

2024-06-24 00:31 UTC, coffeephile commented
@farnabaz Many thanks for your swift review, much appreciated! 🙏 

I've implemented the changes you suggested, please check again 🙇‍♂️

2024-06-25 08:37 UTC, farnabaz approved these changes
LGTM 👍 
Thanks

2024-06-25 08:38 UTC, merged

2024-06-25 22:31 UTC, coffeephile commented
Thank you! 🙏😊