WIP docs: spelling mistakes in the migration guide
nuxt/content pull request #2908
Opened 2024-12-11 21:35 UTC by puzzle-it-nu

### 🔗 Linked issue
#2907 
### ❓ Type of change
Fix spelling mistakes

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Fixes what I think are some spelling mistakes.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2024-12-11 22:49 UTC, farnabaz approved these changes

2024-12-11 22:50 UTC, farnabaz commented
Thanks for the PR, 
I'll wait for you to move it out of WIP

2024-12-12 21:38 UTC, puzzle-it-nu commented
Question:
There are numbered folders in the `docs/content/docs` folder, from 1 to 7 but the number '3' occurs twice.
Is that correct?

2024-12-13 09:22 UTC, puzzle-it-nu commented
@farnabaz I've made a mistake, commit 794379b should be reverted.
Do I make a revert commit or can I rebase and drop that commit? What is the preferred way todo this.

2024-12-13 09:28 UTC, puzzle-it-nu commented
Things I came across but don't know what to do with:
- frontmatter vs front-matter vs Front Matter
- pascal casing in 'title' frontmatter isn't consistent
- index.md 'write content in md, yaml, json' vs 'md yaml, json, csv' in the example

Spelling in the browser :smile:  says frontmatter should either be `front matter` or `front-matter`

2024-12-13 20:51 UTC, puzzle-it-nu commented
> Nice work @puzzle-it-nu 👍
> 
Thanks.

> > There are numbered folders in the docs/content/docs folder, from 1 to 7 but the number '3' occurs twice.
> 
> It is incorrect, and need to be fixed

Should the second '3' become '4' and so on?

> 
> > Do I make a revert commit or can I rebase and drop that commit? What is the preferred way todo this.
> 
> There isn't any preferred way, do as you prefer :)
> 

Ok, I'm in doubt whether it is really a problem. It looks more a visual indentation than that is has a function.
If the latter is the case then it can stay.

> > frontmatter vs front-matter vs Front Matter
> 
> I think we should use frontmatter all the time, as a single word since it refers to the metadata block

Ok, I'll change that where needed.

> 
> > index.md 'write content in md, yaml, json' vs 'md yaml, json, csv' in the example
> 
> Shall we add csv to index.md?

I'm in favour of that, will add it.

2024-12-13 21:40 UTC, puzzle-it-nu commented
@farnabaz two more questions/'problems'
- point 5 'Deploy' has 3 items but they are not numbered. All the other chapters do have numbered items. My suggestion would be to number them.
- there are a dozen or so files with a frontmatter meta that contains 2 times a `title:`, looking at the content3 site it looks like the second one wins. Problem is I don't know whether the first or second one is the correct one. For example: 5.Deploy/server.md

2024-12-16 15:40 UTC, puzzle-it-nu commented
@farnabaz about the titles makes sense, thanks

2024-12-17 07:45 UTC, farnabaz requested changes

2024-12-17 07:45 UTC, farnabaz commented on docs/content/docs/2.collections/1.collections.md
> +title: Define
```suggestion
  title: Define
```

2024-12-17 07:45 UTC, farnabaz commented on docs/content/docs/2.collections/2.types.md
> +title: Types
```suggestion
  title: Types
```

2024-12-17 07:45 UTC, farnabaz commented on docs/content/docs/2.collections/3.sources.md
> +title: Sources
```suggestion
  title: Sources
```

navigation title should be indented

2024-12-17 07:45 UTC, farnabaz commented on docs/content/docs/3.files/2.yaml.md
> +// TODO: should `stem` be `name`?
`stem` is the file name without extension. we can keep stem

2024-12-17 07:45 UTC, farnabaz commented on docs/content/docs/3.files/3.json.md
> +// TODO: should `stem` be `name`?
`stem` is the file name without extension. we can keep stem

2024-12-18 19:20 UTC, puzzle-it-nu commented on docs/content/docs/2.collections/1.collections.md
> +title: Define
Suggestion added

2024-12-18 19:20 UTC, puzzle-it-nu commented on docs/content/docs/2.collections/2.types.md
> +title: Types
Suggestion added

2024-12-18 19:21 UTC, puzzle-it-nu commented on docs/content/docs/2.collections/3.sources.md
> +title: Sources
Suggestion added

2024-12-18 19:34 UTC, puzzle-it-nu commented
@farnabaz added your changes and also added numbering and fixed the double '3'

There are still a few spots where the wording feels odd to me but I'm not a native english speaker so that could just me.

2024-12-20 00:55 UTC, farnabaz approved these changes
LGTM 👍 
Thanks

2024-12-20 00:56 UTC, merged