remark-gfm dependency added to manage markdown tables
nuxt/content pull request #654
Opened 2020-11-21 19:10 UTC by paolodenti

Fix for [issue 653](https://github.com/nuxt/content/issues/653)

Markdown tables not rendered in 9.0.0

## Types of changes

- [x ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
new dependency added: `remark-gfm`
use of new dependency added:

```
const gfm = require('remark-gfm')

let stream = unified().use(parse).use(gfm)
```

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

2020-11-23 10:11 UTC, benjamincanac requested changes
Thanks for the PR, I wasn't aware that `remark-parse` was not handling `gfm` anymore.

2020-11-23 10:11 UTC, benjamincanac commented on package.json
> +    "remark-gfm": "^1.0.0"
This dependency should be added in the `package.json` of the content package located here https://github.com/nuxt/content/blob/dev/packages/content/package.json.

2020-11-23 10:11 UTC, benjamincanac commented on packages/content/parsers/markdown/index.js
> +      let stream = unified().use(parse).use(gfm)
The `remark-gfm` plugin should be added here https://github.com/nuxt/content/blob/dev/packages/content/lib/utils.js#L14 to not break options override.

2020-11-24 00:30 UTC, paolodenti commented
@benjamincanac 
the tests are failing while "fetching packets", network issues. I do not know how they can be triggered again.

2020-11-24 12:57 UTC, benjamincanac approved these changes

2020-11-24 13:10 UTC, merged

2020-11-24 13:10 UTC, benjamincanac commented
@paolodenti I relaunched the tests, all good 👍